name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         ssh-key: ${{ secrets.PRIVATE_REPOSITORY }}
         repository: mosama90/two

    - name: Fetch changes from mirror
      run: |
        git remote add mirror git@github.com:mosama90/one.git
        git fetch mirror

    - name: Merge changes
      run: git merge mirror/main

    - name: Push changes to original repository
      run: git push origin main
