name: Mirror to Another Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add mirror https://github.com/mosama90/one.git

    - name: Push changes to mirror repository
      run: |
        git push mirror main
      env:
        GH_TOKEN: ${{ secrets.MIRROR_PAT }}
