name: Mirror Changes to mosama90/one

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Mirror changes
      run: |
        git remote add mirror https://github.com/mosama90/one.git
        git push mirror HEAD:main
      env:
        GH_TOKEN: ${{ secrets.MIRROR_PAT }}
