name: Test

on:
  push:
    branches:
      - test/action

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"
      ROS_DISTRO: noetic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download selected private repository dependencies
        run: |
          mkdir -p ~/catkin_workspace/src
          cd ~/catkin_workspace/src
          ssh-agent sh -c 'echo "${{ secrets.PRIVATE_REPOSITORY }}" | ssh-add - && git clone git@github.com:mosama90/two.git'
