name: Clone and Display Private Repo

on:
  push:
    branches:
      - main

jobs:
  clone_and_display:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: mosama90/two
        token: ${{ secrets.GIT}}  # Use GitHub provided token for authentication

    - name: Display File Contents
      run: |
        cd $GITHUB_WORKSPACE/two
        cat test
