name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         ssh-key: ${{ secrets.PRIVATE_REPOSITORY }}
         repository: mosama90/two

    - name: Fetch changes from mirror
      run: |
        git remote add mirror git@github.com:mosama90/one.git
        git fetch mirror
    - name: Set up Git
      run: |
       git config --global user.email "o.moussi@arribatt.com"
       git config --global user.name "omar moussi"
    - name: Merge changes
      run: git merge --allow-unrelated-histories mirror/main

    - name: Push changes to original repository
      run: git push origin main
