name: Clone and Display Private Repo

on:
  push:
    branches:
      - main

jobs:
  clone_and_display:
    runs-on: ubuntu-latest

    steps:
    - name: moussi omar repo 
      uses: actions/checkout@v2
      with:
        owner: 'mosama90'
        repository: 'two'
        access-token: ${{ secrets.GIT }}
