name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         ssh-key: ${{ secrets.PRIVATE_REPOSITORY }}
         repository: mosama90/two

    - name: Mirror changes
      run: |
        git remote add mirror https://github.com/mosama90/one.git
        git push mirror HEAD:main
 
