name: Clone and Display

on:
  push:
    branches:
      - main

jobs:
  clone_and_display:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
       

    - name: Display File Contents
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/mosama90/one.git
        cd one
        cat test
